### PR TITLE
ETL Job FSM & ETL Column Selection

### LINKED ISSUE #97: ETL Job FSM
We've got some hacked in state functions for ETL Jobs. I'd like to see this converted to a FSM like with what we did on the Meta schema.

- [ ] FSM added to schema
- [ ] changesets updated
- [ ] actions updated

### LINKED ISSUE #138: Ingest Error when Input Cols !== DS Fields
if a table has fewer fields than the input data, it will fail. this may or may not be a bad thing. i tried setting up a table with only a few columns that i wanted from a data set rather than adding all of them.

```
** (Postgrex.Error) ERROR 42601 (syntax_error): INSERT has more expressions than target columns
    (ecto) lib/ecto/adapters/sql.ex:200: Ecto.Adapters.SQL.query!/5
    (plenario2) lib/plenario2_etl/worker.ex:220: Plenario2Etl.Worker.template_query!/3
    (plenario2) lib/plenario2_etl/worker.ex:95: Plenario2Etl.Worker.load_chunk!/4
```

### PR DESCRIPTION
**Pull request by HeyZoos**
### Major Changes
- Formalize etl job state transition functions through a fsm (closes #97)
- Perform etl on exactly the columns provided by `meta` (closes #138)

### Minor Changes
- Include gdal in apt dependencies so we can test shapefile etl
- Test all of the above

### Notes
- There is a gdal error that is being printed that does not appear when running on either of my development machines, it doesn't fail the test however, so maybe it's because of the gdal version used by travis
- The tzdata issue (#143) does not appear for my latest build?
- The genserver error is intentionally thrown and caught by one of the fsm tests, we could turn it off by tweaking `config/test.exs` if we like

### CODE REVIEW

File: lib/plenario2/actions/etl_job_actions.ex [hunk 1]
```diff
@@ -72,21 +73,23 @@ defmodule Plenario2.Actions.EtlJobActions do
     Repo.all(from(job in EtlJob, where: job.meta_id == ^meta_id))
   end
 
-  # TODO: this should be converted to an FSM function on the schema, a la Meta states
   def mark_started(job) do
-    EtlJobChangesets.mark_started(job)
+    EtlJob.mark_started(job)
+    |> put_change(:started_on, DateTime.utc_now())
```
Comment (vforgione) [inline lib/plenario2/actions/etl_job_actions.ex]: This feels gross... maybe bake this into the changeset:

```elixir
# EtlJobChangeset.ex

def mark_started(job) do
  job
  |> EtlJob.mark_started()  # returns a changeset
  |> set_started()
end

defp set_started(changeset), do: put_change(changeset, :started_on, DateTime.utc_now())

defp set_completed(changeset), do: put_change(changeset, :completed_on, DateTime.utc_now())
```
