### PR TITLE
Use `DateTime.compare/2` instead of `>` operator

### LINKED ISSUE #310: Form validation error is incorrect
image

### PR DESCRIPTION
**Pull request by HeyZoos**
>Remember, comparisons in Elixir using ==, >, < and friends are structural and based on the DateTime struct fields. For proper comparison between datetimes, use the compare/2 function.

Herpaderp.

- Close #310 
- Bump to version `0.9.3`

### CODE REVIEW

File: lib/plenario_web/controllers/web/page_controller.ex [hunk 1]
```diff
@@ -19,8 +19,15 @@ defmodule PlenarioWeb.Web.PageController do
...
     {startdt, conn} = parse_date(conn, starts)
     {enddt, conn} = parse_date(conn, ends)
-
-    do_explorer(zoom, coords, startdt, enddt, conn)
+    comparison = DateTime.compare(startdt, enddt)
+
+    case DateTime.compare(startdt, enddt) do
+      :gt ->
+        do_explorer(zoom, coords, startdt, enddt, put_flash(conn, :error,
+          "The starting datetime #{startdt} cannot be greater than the ending datetime #{enddt}"))
```
Comment (brlodi) [inline lib/plenario_web/controllers/web/page_controller.ex]: While we're in here making changes, perhaps it's worth applying a formatterto the date display in the flash. This doesn't exactly scream user-friendly, and they'll never have time components anyway:

> The starting datetime 2018-05-16 00:00:00.0Z cannot be greater than the ending datetime 2018-05-16 00:00:00.0Z

File: test/plenario_web/controllers/web/page_controller_test.exs [hunk 2]
```diff
@@ -170,6 +170,9 @@ defmodule PlenarioWeb.Web.Testing.PageControllerTest do
   test "explorer receives start datetime greater than end datetime", %{conn: conn} do
     conn = get(conn, page_path(conn, :explorer), %{"starting_on" => "3000-01-01", "ending_on" => "2000-01-01"})
     assert get_flash(conn)["error"] =~ "cannot be greater than"
+
+    conn = get(conn, page_path(conn, :explorer), %{"starting_on" => "2018-03-31", "ending_on" => "2018-05-01"})
+    assert get_flash(conn)["error"] =~ "cannot be greater than"
```
Comment (brlodi) [inline test/plenario_web/controllers/web/page_controller_test.exs]: I'm guessing you probably want to assert that there _isn't_ a flash, since 2018-03-31 is before 2018-05-01

Comment (HeyZoos) [reply test/plenario_web/controllers/web/page_controller_test.exs]: Yep, good catch.

File: test/plenario_web/controllers/web/page_controller_test.exs [hunk 3]
```diff
@@ -177,4 +197,10 @@ defmodule PlenarioWeb.Web.Testing.PageControllerTest do
     conn = get(conn, page_path(conn, :explorer), %{"starting_on" => "woopwoop", "ending_on" => "2000-01-01"})
     assert get_flash(conn)["error"] =~ "Invalid date woopwoop"
   end
+
+   @tag :anon
+  test "explorer receives a terribly fake date", %{conn: conn} do
+    conn = get(conn, page_path(conn, :explorer), %{"starting_on" => "2000-01-01", "ending_on" => "2000-19-11"})
```
Comment (brlodi) [inline test/plenario_web/controllers/web/page_controller_test.exs]: Ahh yes, the fabled nineteenth month AKA Septendecember

Comment (HeyZoos) [reply test/plenario_web/controllers/web/page_controller_test.exs]: beware the ides of septendecember
