### PR TITLE
Struct/ID Agnostic Actions and Fix Nasty Date Comp Bug

### LINKED ISSUE #92: `meta` vs `meta_id`
As I've been documenting the libs, I keep seeing switches in parameters. Here's 3 ideas on how to fix it:

1. we standardize on `meta_id` or `${whatever schema name}_id` as the param
1. we standardize on passing the instance
1. we keep both, have 2 functions with guard clauses

I like the last one -- it gives us the maximum flexibility. For example:

```elixir
def list_for_meta(meta) when not is_integer(meta) do
  list_for_meta(meta.id)
end

def list_for_meta(meta_id) when is_integer(meta_id) do
  ...
end
```

Thoughts from @HeyZoos and @sanilio?

### LINKED ISSUE #103: Failing Test
This didn't fail in the past but it suddenly is now...

```
  1) test bad refresh info (MetaActionsTests)
     test/plenario2/meta_actions_test.exs:153
     ** (MatchError) no match of right hand side value: {:ok, %Plenario2.Schemas.Meta{__meta__: #Ecto.Schema.Metadata<:loaded, "metas">, admin_user_notes: #Ecto.Association.NotLoaded<association :admin_user_notes is not loaded>, attribution: nil, bbox: nil, data_set_constraints: #Ecto.Association.NotLoaded<association :data_set_constraints is not loaded>, data_set_diffs: #Ecto.Association.NotLoaded<association :data_set_diffs is not loaded>, data_set_fields: #Ecto.Association.NotLoaded<association :data_set_fields is not loaded>, description: nil, etl_jobs: #Ecto.Association.NotLoaded<association :etl_jobs is not loaded>, export_jobs: #Ecto.Association.NotLoaded<association :export_jobs is not loaded>, first_import: nil, id: 5542, inserted_at: ~N[2018-01-05 15:26:36.089952], latest_import: nil, name: "Chicago Tree Trimming", next_refresh: nil, refresh_ends_on: ~D[2017-12-05], refresh_interval: nil, refresh_rate: nil, refresh_starts_on: ~D[2018-01-05], slug: "k-CLH0MWlrmc41_s", source_type: "csv", source_url: "https://www.example.com/chicago-tree-trimming", srid: 4326, state: "new", timerange: nil, timezone: "UTC", updated_at: ~N[2018-01-05 15:26:36.089958], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_id: 10684, virtual_date_fields: #Ecto.Association.NotLoaded<association :virtual_date_fields is not loaded>, virtual_point_fields: #Ecto.Association.NotLoaded<association :virtual_point_fields is not loaded>}}
     code: {:error, changeset} = MetaActions.create(
     stacktrace:
       test/plenario2/meta_actions_test.exs:170: (test)
```

### PR DESCRIPTION
**Pull request by vforgione**
closes #92 
fixes #103

### CODE REVIEW

File: lib/plenario2/actions/data_set_constraint_actions.ex [hunk 1]
```diff
@@ -6,15 +6,33 @@ defmodule Plenario2.Actions.DataSetConstraintActions do
...
   """
-  @spec create(meta_id :: integer, field_names :: [String.t]) :: {:ok, %DataSetConstraint{} | :error, Ecto.Changeset.t}
-  def create(meta_id, field_names) do
+  @spec create(meta :: Meta | id, field_names :: [String.t]) :: ok_constr
+  def create(meta, field_names) do
+    meta_id =
+      case is_id(meta) do
+        true -> meta
+        false -> meta.id
+      end
```
Comment (HeyZoos) [inline lib/plenario2/actions/data_set_constraint_actions.ex]: Could be more succinct  as two heads of the same function.

```elixir
def create(meta, fields) when !is_id(meta), do: create(meta.id, fields)
def create(meta_id, fields) do
  # work with id
end
```

Both ways you've done it are readable, but using function guards over case is more elixir(ific? tastic?) I believe

File: lib/plenario2/actions/data_set_diff_actions.ex [hunk 2]
```diff
@@ -6,15 +6,45 @@ defmodule Plenario2.Actions.DataSetDiffActions do
...
+      case is_id(constraint) do
+        true -> constraint
+        false -> constraint.id
+      end
+
+    etl_job_id =
+      case is_id(etl_job) do
+        true -> etl_job
+        false -> etl_job.id
+      end
```
Comment (HeyZoos) [inline lib/plenario2/actions/data_set_diff_actions.ex]: Same thing, just add more heads and they'll eventually call the correct one. As long as the call to create is the last piece of work done, we don't build out a recursive call stack.

```elixir
def create(meta, constraint, job, fields) when !is_id(meta), do: create(meta.id, constraint, job, fields)
def create(meta, constraint, job, fields) when !is_id(constraint), do: create(meta, constraint.id, job fields)
def create(meta, constraint, job, fields) when !is_id(job), do: create(meta, constraint, job.id, fields)
def create(meta_id, fields) do
  # work with ids
end
```
